spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.53.238.46:5432/pob
    username: postgres
    password: 78290@beggar.ten

logging:
  file:
    path: log

pob:
  swagger-ui: http://120.53.238.46