spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pob
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    # 程序启动后根据 Entity 创建表
#    generate-ddl: true

logging:
  level:
    # 打印 RestTemplate 请求和相应
    com.tenbeggar.pob.config.LoggingInterceptor: debug

pob:
  swagger-ui: http://localhost